---
steps:
  - name: sdesbure/yamllint
    id: yamllint
    waitFor: ['-']
    args:
      - /workspace/cloudbuild.yaml

  - name: asia-northeast1-docker.pkg.dev/effective-carnival/registry/staticcheck
    id: staticcheck
    waitFor: ['-']
    entrypoint: staticcheck
    args:
      - ./...

  - name: gcr.io/kaniko-project/executor:latest
    id: docker
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --context=helloworld
      - --destination=asia-northeast1-docker.pkg.dev/effective-carnival/registry/helloworld:$COMMIT_SHA
      - --destination=asia-northeast1-docker.pkg.dev/effective-carnival/registry/helloworld:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: deploy
    waitFor: ['docker']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - example
      - --image
      - asia-northeast1-docker.pkg.dev/effective-carnival/registry/helloworld:$COMMIT_SHA
      - --region
      - asia-northeast1
      - --min-instances
      - "0"
      - --max-instances
      - "1"
