steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/effective-carnival/registry/staticcheck:latest
